== Introduction and Goals

This document describes the Traffic Pursuit Unit, short TPU, which is a speed measuring device equipped with video recording facilities that is installed within a policecar. It is used to measure and record the speed profile of a car driving in front of the policecar, so that speed limit violations can be proved and legal action can be taken based on the documentation and video recordings produced by the system. The current development is based on an existing version of the system, that has been developed by the same companies, and shall take the product to a new release with added and improved featurers enabled by the latest developments in hardware technology.

The following goals have been established for this system:

[frame=ends, cols="10h,~,~"]
|===
|Priority |

|1
|The system shall be enhanced by features that are suitable to keep and strenghten the position as the current market leader

|2
|The system shall implement HD resolution for video clips and storage of the clips to harddisk.

|3
|All system parts that are due to legal approval shall be contained in one unit (called MeasuringUnit), so that replacement of other parts of the system will not require reapproval of the device.

|4
|All system parts that are due to legal approval shall be contained in one unit (called MeasuringUnit), so that replacement of other parts of the system will not require reapproval of the device.

|5
|The operable temperature range shall be expanded to a range of at least -25 to 85 degrees Celsius.
|===
