== Introduction and Goals

This document describes the Spacevis Platform, which is a solution for mitigating problems and adding value to the farmers, agribusiness banks, insurance companies and investors.

The Tag is a device that is put in the cattle's ear for their uniq identification and for tracking their position and circulation in a dynamic way. All this data that's captured by a Tag is stored in our databases and in a blockchain infrastructure to guarantee the reliability of the data and for future use.

The frontend platforms are integrated with the Tag and its data, in such a way that farmers can manage the cattle and get their position dynamically.

The main purpose of this structure is to provide more value to the farmers by generating insightful information based on the data captured by the Tags, for a better management of the cattle, usage of the information as a reliable asset to negotiate with financial institutions, usage of the structured blockchain representation of the cattle for future investors and digital economy.

The following goals have been established for this system:

[frame=ends, cols="10h,~"]
|===
|Priority |

|1
|The system shall be enhanced by features that are suitable to keep and strengthen the position as the current market leader

|2
|The system shall implement HD resolution for video clips and storage of the clips to harddisk.

|3
|All system parts that are due to legal approval shall be contained in one unit (called MeasuringUnit), so that replacement of other parts of the system will not require reapproval of the device.

|4
|All system parts that are due to legal approval shall be contained in one unit (called MeasuringUnit), so that replacement of other parts of the system will not require reapproval of the device.

|5
|The operable temperature range shall be expanded to a range of at least -25 to 85 degrees Celsius.
|===
